//From: ftp://ftp.3gpp.org/Specs/2005-03/Rel-6/32_series/32111-3-620.zip
//File: AlarmIRPNotifications.idl

//	Fixed following typos:
// 	Line 50:
//      const string_VENDOR_SPECIFIC_ALARM_TYPE = 
// 	to:
//      const string VENDOR_SPECIFIC_ALARM_TYPE = 

#ifndef _ALARMIRPNOTIFICATIONS_IDL_
#define _ALARMIRPNOTIFICATIONS_IDL_

#include "AlarmIRPConstDefs.idl"
#include "NotificationIRPConstDefs.idl"
#include "NotificationIRPNotifications.idl"

// This statement must appear after all include statements
#pragma prefix "3gppsa5.org"

/* ## Module: AlarmIRPNotifications
This module contains notifications for Alarm IRP
================================================================
*/

module AlarmIRPNotifications
{

   interface NotifyNewAlarm: NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyNewAlarm";

      /**
       * This constant defines the name of the probableCause property. 
       * The data type for the value of this property
       * is short.
       */
      const string PROBABLE_CAUSE = 
         AlarmIRPConstDefs::AttributeNameValue::PROBABLE_CAUSE;

      /**
       * This constant defines the name of the 
       * perceivedSeverity property.
       * The data type for the value of this property
       * is short.
       */
      const string PERCEIVED_SEVERITY = 
         AlarmIRPConstDefs::AttributeNameValue::PERCEIVED_SEVERITY;

      /**
       * This constant defines the name of the specificProblem
       * property.  The data type for the value of this property
       * is string.
       */

      const string VENDOR_SPECIFIC_ALARM_TYPE = 
         AlarmIRPConstDefs::AttributeNameValue::VENDOR_SPECIFIC_ALARM_TYPE;

      /**
This constant identifies the NE alarm type or NE related alarm type.
The data type for the value of this property is string.
       */

      const string SPECIFIC_PROBLEM = 
         AlarmIRPConstDefs::AttributeNameValue::SPECIFIC_PROBLEM;

      /**
       * This constant defines the name of the 
       * correlatedNotifications property.
       * The data type for the value of this property
       * is AlarmIRPConstDefs::CorrelatedNotificationSetType.
       */
      const string CORRELATED_NOTIFICATIONS =
        AlarmIRPConstDefs::AttributeNameValue::
          CORRELATED_NOTIFICATIONS;
      
      /**
       * This constant defines the name of the 
       * backedUpStatus property.
       * The data type for the value of this property
       * is AlarmIRPConstDefs::BackedUpStatusType.
       */
      const string BACKED_UP_STATUS = 
         AlarmIRPConstDefs::AttributeNameValue::BACKED_UP_STATUS;
      
      /**
       * This constant defines the name of the backUpObject property.
       * The data type for the value of this property
       * is a string carrying of DN of the back-up object.
       */
      const string BACK_UP_OBJECT = 
         AlarmIRPConstDefs::AttributeNameValue::BACK_UP_OBJECT;
      
      /**
       * This constant defines the name of the 
       * trendIndication property. 
       * The data type for the value of this property
       * is AlarmIRPConstDefs::TrendIndicationType.
       */
      const string TREND_INDICATION = 
         AlarmIRPConstDefs::AttributeNameValue::TREND_INDICATION;
      
      /**
       * This constant defines the name of the thresholdInfo property.
       * The data type for the value of this property
       * is AlarmIRPConstDefs::ThresholdInfoType.
       */
      const string THRESHOLD_INFO = 
         AlarmIRPConstDefs::AttributeNameValue::THRESHOLD_INFO;

      /**
       * This constant defines the name of the 
       * stateChangeDefinition property.
       * The data type for the value of this property
       * is AlarmIRPConstDefs::AttributeChangeSetType.
       */
      const string STATE_CHANGE_DEFINITION = 
        AlarmIRPConstDefs::AttributeNameValue::STATE_CHANGE_DEFINITION;

      /**
       * This constant defines the name of the 
       * monitoredAttributes property.
       * The data type for the value of this property
       * is AlarmIRPConstDefs::AttributeSetType.
       */
      const string MONITORED_ATTRIBUTES = 
         AlarmIRPConstDefs::AttributeNameValue::MONITORED_ATTRIBUTES;

      /**
       * This constant defines the name of the 
       * proposedRepairActions property.
       * The data type for the value of this property
       * is string.
       */
      const string PROPOSED_REPAIR_ACTIONS = 
        AlarmIRPConstDefs::AttributeNameValue::PROPOSED_REPAIR_ACTIONS;

      /**
       * This constant defines the name of the additiionalText
       * property.
       * The data type for the value of this property
       * is string.
       */
      const string ADDITIONAL_TEXT = 
         AlarmIRPConstDefs::AttributeNameValue::ADDITIONAL_TEXT;

      /**
       * This constant defines the name of the alarmId property.
       * The data type for the value of this property
       * is string.  If the string is a zero-length string or if 
       * this NV pair is absent, the default semantics is that 
       * alarmId is a concatenation of 
       * managedObjectInstance, eventType, probableCause and
       * specificProblem, if present, of this Structured Event. 
       * Since probableCause is encoded as a short, it shall be
       * converted into string before concatenation. 
       * The resultant string shall not contain spaces.
       */
      const string ALARM_ID = 
        AlarmIRPConstDefs::AttributeNameValue::ALARM_ID;

      /**
       * This constant defines the name of the serviceUser property.
       * The data type for the value of this property
       * is string.
       */
      const string SERVICE_USER = 
         AlarmIRPConstDefs::AttributeNameValue::SERVICE_USER;

      /**
       * This constant defines the name of the serviceProvider
       * property. 
       * The data type for the value of this property
       * is string.
       */
      const string SERVICE_PROVIDER = 
         AlarmIRPConstDefs::AttributeNameValue::SERVICE_PROVIDER;

      /**
       * This constant defines the name of the 
       * securityAlarmDetector property. 
       * The data type for the value of this property
       * is string.
       */
      const string SECURITY_ALARM_DETECTOR = 
        AlarmIRPConstDefs::AttributeNameValue::SECURITY_ALARM_DETECTOR;
   };


   interface NotifyAckStateChanged:
       NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyAckStateChanged";

      const string PROBABLE_CAUSE = 
         AlarmIRPConstDefs::AttributeNameValue::PROBABLE_CAUSE;

      const string PERCEIVED_SEVERITY = 
         AlarmIRPConstDefs::AttributeNameValue::PERCEIVED_SEVERITY;

      const string ALARM_ID = 
         AlarmIRPConstDefs::AttributeNameValue::ALARM_ID;

      /**
       * This constant defines the name of the ackTime property. 
       * The data type for the value of this property
       * is ManagedGenericIRPConstDefs::IRPTime.
       */
      const string ACK_TIME = 
        AlarmIRPConstDefs::AttributeNameValue:: ACK_TIME;

      const string ACK_USER_ID = 
         AlarmIRPConstDefs::AttributeNameValue::ACK_USER_ID;

      const string ACK_SYSTEM_ID = 
         AlarmIRPConstDefs::AttributeNameValue::ACK_SYSTEM_ID;

      const string ACK_STATE =
          AlarmIRPConstDefs::AttributeNameValue::ACK_STATE;

   };


   interface NotifyClearedAlarm: NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyClearedAlarm";

      const string PROBABLE_CAUSE = 
         AlarmIRPConstDefs::AttributeNameValue::PROBABLE_CAUSE;

      const string PERCEIVED_SEVERITY = 
         AlarmIRPConstDefs::AttributeNameValue::PERCEIVED_SEVERITY;

      const string ALARM_ID =
        AlarmIRPConstDefs::AttributeNameValue::ALARM_ID;

      const string CLEAR_USER_ID = 
         AlarmIRPConstDefs::AttributeNameValue::CLEAR_USER_ID;

      const string CLEAR_SYSTEM_ID = 
         AlarmIRPConstDefs::AttributeNameValue::CLEAR_SYSTEM_ID;
   };


   interface NotifyAlarmListRebuilt:
       NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyAlarmListRebuilt";

      const string REASON =
        AlarmIRPConstDefs::AttributeNameValue::REASON;

      const string ALARM_LIST_ALIGNMENT_REQUIREMENT =
        AlarmIRPConstDefs::AttributeNameValue::
          ALARM_LIST_ALIGNMENT_REQUIREMENT;
   };


   interface NotifyChangedAlarm: NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyChangedAlarm";

      const string PROBABLE_CAUSE = 
         AlarmIRPConstDefs::AttributeNameValue::PROBABLE_CAUSE;

      const string PERCEIVED_SEVERITY = 
         AlarmIRPConstDefs::AttributeNameValue::PERCEIVED_SEVERITY;

      const string ALARM_ID =
        AlarmIRPConstDefs::AttributeNameValue::ALARM_ID;


   };


   interface NotifyComments: NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyComments";

      const string PROBABLE_CAUSE = 
         AlarmIRPConstDefs::AttributeNameValue::PROBABLE_CAUSE;

      const string PERCEIVED_SEVERITY = 
         AlarmIRPConstDefs::AttributeNameValue::PERCEIVED_SEVERITY;

      const string ALARM_ID =
        AlarmIRPConstDefs::AttributeNameValue::ALARM_ID;

      /**
       * This constant defines the name of the comments property. 
       * The data type for the value of this property
       * is AlarmIRPConstDefs::CommentSet.
       */
      const string COMMENTS =
        AlarmIRPConstDefs::AttributeNameValue::COMMENTS;
   };


   interface NotifyPotentialFaultyAlarmList:
       NotificationIRPNotifications::Notify
   {
      const string EVENT_TYPE = "notifyPotentialFaultyAlarmList";

      /**
       * This constant defines the name of the reason property. 
       * The data type for the value of this property
       * is string.
       */      
      const string REASON =
        AlarmIRPConstDefs::AttributeNameValue::REASON;
   };

};

#endif // _ALARMIRPNOTIFICATIONS_IDL

