//From: ftp://ftp.3gpp.org/Specs/2005-03/Rel-6/32_series/32643-640.zip
//File:UtranNetworkResourcesNRMDefs.idl
#ifndef _UTRANNETWORKRESOURCESNRMDEFS_IDL_
#define _UTRANNETWORKRESOURCESNRMDEFS_IDL_
#include "GenericNetworkResourcesNRMDefs.idl"
#pragma prefix "3gppsa5.org"

/**
 * This module defines constants for each MO class name and
 * the attribute names for each defined MO class.
 */
module UtranNetworkResourcesNRMDefs
{
      



      /**
       *  Definitions for MO class RncFunction
       */ 
      interface RncFunction : GenericNetworkResourcesNRMDefs::ManagedFunction
      {
         const string CLASS = "RncFunction";

         // Attribute Names
         // 
         const string rncFunctionId = "rncFunctionId";
         const string mcc= "mcc";
         const string mnc= "mnc";
         const string rncId= "rncId";
      };


      /**
       *  Definitions for MO class UtranCell
       */ 
      interface UtranCell : GenericNetworkResourcesNRMDefs::ManagedFunction 
      {
         const string CLASS = "UtranCell";

         // Attribute Names
         //         
         const string utranCellId = "utranCellId";
         const string utranCellIubLink = "utranCellIubLink";
         const string cId= "cId";
         const string localCellId= "localCellId";
         const string uarfcnUl= "uarfcnUl";
         const string uarfcnDl= "uarfcnDl";
         const string primaryScramblingCode= "primaryScramblingCode";
         const string primaryCpichPower= "primaryCpichPower";
         const string maximumTransmissionPower= "maximumTransmissionPower";
         const string retAntennaFunctionList= "retAntennaFunctionList";
         const string primarySchPower= "primarySchPower";
         const string secondarySchPower= "secondarySchPower";
         const string bchPower= "bchPower";
         const string cellMode = "cellMode";
         const string uarfcn= "uarfcn";
         const string cellParameterId= "cellParameterId";
         const string primaryCcpchPower= "primaryCcpchPower";
         const string dwPchPower= "dwPchPower";
         const string timeSlotList= "timeSlotList";
         const string schPower= "schPower";
         const string lac= "lac";
         const string rac= "rac";
         const string sac= "sac";
         const string uraList= "uraList";
         const string operationalState = "operationalState";

      };
      
      interface AntennaFunction : GenericNetworkResourcesNRMDefs::ManagedFunction
      {         
         const string CLASS= "AntennaFunction";

         // Attribute Names
         //          
         const string antennaId= "antennaFunctionId";
         const string retUtranCellList= "retUtranCellList";
         const string retTiltValue= "retTiltValue";
         const string compassDirection= "compassDirection";
         const string maxTiltValue= "maxTiltValue";
         const string minTiltValue= "minTiltValue";
         const string mechanicalOffset= "mechanicalOffset";
         const string retGroupName= "retGroupName";
         const string height= "height";
      };
           
      
      /**
       *  Definitions for MO class NodeBFunction
       */
      interface NodeBFunction : GenericNetworkResourcesNRMDefs::ManagedFunction
      {         
         const string CLASS = "NodeBFunction";

         // Attribute Names
         //          
         const string nodeBFunctionId = "nodeBFunctionId";
         const string nodeBFunctionIubLink = "nodeBFunctionIubLink";
      };

      
      /**
       *  Definitions for MO class IubLink
       */
      interface IubLink : GenericNetworkResourcesNRMDefs::ManagedFunction 
      {
         const string CLASS = "IubLink";

         // Attribute Names
         //          
         const string iubLinkId = "iubLinkId";
         const string iubLinkNodeBFunction = "iubLinkNodeBFunction";
         const string iubLinkUtranCell = "iubLinkUtranCell";
         const string iubLinkATMChannelTerminationPoint = "iubLinkATMChannelTerminationPoint";
         
      };

};


      /**
       *  Definitions for MO class UtranRelation
       */ 
      interface UtranRelation : GenericNetworkResourcesNRMDefs::Top 
      {
         const string CLASS = "UtranRelation";

         // Attribute Names
         //         
         const string utranRelationId = "utranRelationId";
         const string adjacentCell = "adjacentCell";
         const string uarfcnUl= "uarfcnUl";
         const string uarfcnDl= "uarfcnDl";
         const string primaryScramblingCode= "primaryScramblingCode";
         const string primaryCpichPower= "primaryCpichPower";
         const string cellMode = "cellMode";
         const string uarfcn= "uarfcn";
         const string cellParameterId= "cellParameterId";
         const string primaryCcpchPower= "primaryCcpchPower";
         const string lac= "lac";
};


/**
       *  Definitions for MO class ExternalUtranCell
       */ 
      interface ExternalUtranCell  : GenericNetworkResourcesNRMDefs::ManagedFunction
      {
         const string CLASS = "ExternalUtranCell";

         // Attribute Names
         //         
         const string externalUtranCellId = "externalUtranCellId";
         const string cId= "cId";
         const string mcc= "mcc";
         const string mnc= "mnc";
         const string rncId= "rncId";
         const string uarfcnUl= "uarfcnUl";
         const string uarfcnDl= "uarfcnDl";
         const string primaryScramblingCode= "primaryScramblingCode";
         const string primaryCpichPower= "primaryCpichPower";
         const string cellMode = "cellMode";
         const string uarfcn= "uarfcn";
         const string cellParameterId= "cellParameterId";
         const string primaryCcpchPower= "primaryCcpchPower";
         const string lac= "lac";
         const string rac= "rac";
         const string controllingRnc = "controllingRnc";

      };


      /**
       *  Definitions for MO class ExternalRncFunction
       */
      interface ExternalRncFunction :
         GenericNetworkResourcesNRMDefs::ManagedFunction
      {
         const string CLASS = "ExternalRncFunction";

         // Attribute Names
         //
         const string externalRncFunctionId = "externalRncFunctionId";
         const string mcc = "mcc";
         const string mnc = "mnc";
         const string rncId = "rncId";
         const string controlledCellList = "controlledCellList";

      };

/**
    *  This module adds datatype definitions for both FDD and TDD mode
    *  attributes used in the NRM which are not the basic datatypes 
    *  already defined in CORBA. 
    */
module GenericNRMAttributeTypes
{

      enum CellModeEnumType
      {
         FDDMode, 
         TDDMode_1_28Mcps,
         TDDMode_3_84Mcps
      };

};

/**
    *  This module adds datatype definitions for TDD mode attributes
    *  used in the NRM which are not the basic datatypes already defined
    *  in CORBA. 
    */
   module TDDNRMAttributeTypes
   {

      enum TimeSlotDirectionType
      {
         UL, 
         DL
      };

      enum TimeSlotStatusType
      {
         Active, 
         Not_Active
      };

      struct TimeSlotConfigStructType
      {
         short timeSlotId;
         TimeSlotDirectionType timeSlotDirection;
         TimeSlotStatusType timeSlotStatus;
      };

      typedef sequence<TimeSlotConfigStructType> TimeSlotListConfigStructType;

   };

#endif //_UTRANNETWORKRESOURCESNRMDEFS_IDL_

